// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phqtdczpawzuvdpbxarn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocXRkY3pwYXd6dXZkcGJ4YXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODI0OTMsImV4cCI6MjA2MDc1ODQ5M30.khlMFI2z55h7FvYeYt7Nm0gU8Bm9W5vehqVNG6a5HjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);